#[frontend] → [middleware] → [backend]
#                   ↓             ↓
#                [redis] ←––––––––
version: "3.9"

networks:
  frontend-network:
    driver: bridge
  middleware-network:
    driver: bridge
  backend-network:
    driver: bridge

  global-network:
    driver: bridge

services:

  frontend-core:
    build: frontend/core
    command: python main.py
    ports:
      - "6459:6459"
    expose:
      - "6459"
    networks:
      - frontend-network
      - middleware-network
      - global-network
    env_file:
      - .env

  frontend-telegram:
    build: frontend/telegram
    command: python main.py
    expose:
      - "6541"
    networks:
      - frontend-network
    env_file:
      - .env
    depends_on:
      - frontend-core

  frontend-web:
    build: frontend/web
    command: python main.py
    expose:
      - "5713"
    networks:
      - frontend-network
    env_file:
      - .env
    depends_on:
      - frontend-core

  middleware-core:
    build: middleware/core
    command: ./middleware-core
    expose:
      - "6132"
    networks:
      - middleware-network
      - global-network
    depends_on:
      - middleware-bybit
      - redis
      - middleware-backend
    env_file:
      - .env

  middleware-bybit:
    build: middleware/bybit
    command: ./middleware-bybit
    expose:
      - "6135"
    networks:
      - middleware-network
    env_file:
      - .env

  middleware-backend:
    build: middleware/backend
    command: ./middleware-backend
    expose:
      - "6134"
    networks:
      - middleware-network
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    volumes:
      - ./redisdata:/data
    command: >
      redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
